### ISSUE TITLE
bug: index refers to old about hyperlink

### ISSUE THREAD

**Issue by kylesaburao** [ssss-sfu/ssss-sfu.github.io#6]
/index.html
  **CURRENT** `<li class="nav-item"><a class="nav-link" href="pages/aboutus.html"> About Us </a></li>`
  **INTENDED** `<li class="nav-item"><a class="nav-link" href="pages/aboutus.html"> About Us </a></li>`

Commit `2347bf19`

**Comment by AmirNaghibi** [comment]
@kylesaburao the above **CURRENT** and **INTENDED** are the exact same strings. Did you mean something else?
