### ISSUE TITLE
Add GitHub Logo 

### ISSUE THREAD

**Issue by brianrahadi** [ssss-sfu/ssss-sfu.github.io#81]
We can add GitHub Logo next to Discord on both the header and footer linking to the org (https://github.com/ssss-sfu)

**Comment by devham236** [comment]
hey @brianrahadi, i would love to work on this issue.

**Comment by brianrahadi** [comment]
Hey @devham236 , feel free to take this issue. We are a student society from Simon Fraser University, Canada but open if anyone wants to contribute to it.

**Comment by devham236** [comment]
thanks @brianrahadi, would you mind assigning this issue to me?
