### ISSUE TITLE
Reduce size of SSSS electives page

### ISSUE THREAD

**Issue by CozySchmidt** [ssss-sfu/ssss-sfu.github.io#85]
I like Brian's idea of only showing the name and picture of the execs and then only show their information if clicked on.

**Comment by brianrahadi** [comment]
Initial design via Figma
![image](https://github.com/ssss-sfu/ssss-sfu.github.io/assets/70176191/66e7c8e5-ba8c-4a78-bfca-a87abde92926)

**Comment by brianrahadi** [comment]
Initial design via Figma
![image](https://github.com/ssss-sfu/ssss-sfu.github.io/assets/70176191/c1680e0a-4389-4e89-bbac-3860cc46df29)

**Comment by brianrahadi** [comment]
There will be a toggle click that will set the card into display mode (showing all the text description and making the profile card slightly darkened)

**Comment by brianrahadi** [comment]
![image](https://github.com/ssss-sfu/ssss-sfu.github.io/assets/70176191/9eea9081-56ee-48d1-b0ef-528bb5c45f44)
Current preview
